lib = File.expand_path("..", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "api"
require "carthage_archive"
require "framework_carthage_archive"
require "xcframework_carthage_archive"
require "framework"
require "xcframework"
require "carthage_dependency"
require "constants"
require "configuration"
require "crc32"
require "errors"
require "log"
require "networking"
require "shell_wrapper"
require "table"
require "utils"
require "version"
require "version_file"
