CARTHAGE_DIR = 'Carthage'
CARTHAGE_BUILD_DIR = File.join(CARTHAGE_DIR, 'Build')
CARTFILE_RESOLVED = 'Cartfile.resolved'
CARTRCFILE = 'Cartrcfile'
THREAD_POOL_SIZE = 8

SERVER_DEFAULT_PORT = 9292
SERVER_CACHE_DIR = File.join(Dir.home, '.carthagerc_server')

ARCHIVE_CHECKSUM_HEADER_REST_CLIENT = :archive_checksum
ARCHIVE_CHECKSUM_HEADER_SINATRA_IN = 'HTTP_ARCHIVE_CHECKSUM'
ARCHIVE_CHECKSUM_HEADER_SINATRA_OUT = 'Archive-Checksum'
